-- Rent-a-Blorb -- generated by content_gen/luau_generator.py
-- Core loop: Players hatch, feed, and rent out absurd meme-mashup creatures called Blorbs to other players' bases for short-term buffs; learnable in under 15 minutes.
-- Hook: Instead of a one-off meme cash-grab, Blorbs generate ongoing rental income for their owners, giving the meme premise a light economy that can deepen post-launch (breeding, rare traits) rather than flattening after the initial spike.
-- Economy/social design: The rental marketplace is the core scarcity/trading loop; a breeding sink prevents rental-Blorb inflation; showing off rare Blorbs is the social hook.
-- AI would generate the initial wave of Blorb designs, names, and rental flavor text; a human needs to tune rental payout balance so the economy doesn't inflate within days.

-- Rent-a-Blorb -- server entry point. Wires Remotes, player lifecycle, and the
-- background loops (hunger decay, rental expiry, NPC customers, leaderboard, autosave).

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

-- // Module setup ---------------------------------------------------------------------
-- Wrapped in pcall + WaitForChild timeouts on purpose: a require() error or a missing
-- Instance here used to fail SILENTLY (an unprotected error/infinite yield at the top of
-- a Script just halts the whole script -- nothing after it, including
-- TestWorldBuilder.Build(), ever runs, and Studio's Output panel can be easy to miss).
-- Now any failure here prints loudly and the script bails out cleanly instead of hanging.

local BlorbData, PlayerDataManager, HatchingService, FeedingService, BreedingService,
	RentalService, CustomerSimService, LeaderboardService, BaseAssignmentService, TestWorldBuilder

local setupOk, setupErr = pcall(function()
	BlorbData = require(ReplicatedStorage:WaitForChild("BlorbShared", 10):WaitForChild("BlorbData", 10))
	PlayerDataManager = require(script.Parent:WaitForChild("PlayerDataManager", 10))
	HatchingService = require(script.Parent:WaitForChild("HatchingService", 10))
	FeedingService = require(script.Parent:WaitForChild("FeedingService", 10))
	BreedingService = require(script.Parent:WaitForChild("BreedingService", 10))
	RentalService = require(script.Parent:WaitForChild("RentalService", 10))
	CustomerSimService = require(script.Parent:WaitForChild("CustomerSimService", 10))
	LeaderboardService = require(script.Parent:WaitForChild("LeaderboardService", 10))
	BaseAssignmentService = require(script.Parent:WaitForChild("BaseAssignmentService", 10))
	TestWorldBuilder = require(script.Parent:WaitForChild("TestWorldBuilder", 10))
end)

if not setupOk then
	warn("=====================================================")
	warn("RentABlorb: Main.server.lua FAILED during module setup (require chain):")
	warn(tostring(setupErr))
	warn("This means NONE of the server systems ran this session, including")
	warn("TestWorldBuilder -- that's why Workspace looks empty. Fix the module/")
	warn("path named above and rerun.")
	warn("=====================================================")
	return
end

-- Flip this to false once you've built real level art in Studio to replace the
-- placeholder test world (see TestWorldBuilder.lua / BUILD_NOTES.md).
local BUILD_TEST_WORLD = true

if BUILD_TEST_WORLD then
	local buildOk, buildErr = pcall(function()
		TestWorldBuilder.Build()
	end)

	if not buildOk then
		warn("=====================================================")
		warn("RentABlorb: TestWorldBuilder.Build() FAILED:")
		warn(tostring(buildErr))
		warn("Workspace will stay empty (just Camera/Terrain) until this is fixed.")
		warn("=====================================================")
	else
		print("RentABlorb: TestWorldBuilder.Build() completed OK -- check Workspace.TestWorld.")
	end
end

-- // Remotes setup ------------------------------------------------------------------

local remotesFolder = Instance.new("Folder")
remotesFolder.Name = "Remotes"
remotesFolder.Parent = ReplicatedStorage

local function newRemoteEvent(name)
	local remote = Instance.new("RemoteEvent")
	remote.Name = name
	remote.Parent = remotesFolder
	return remote
end

local BuyAndHatchEggRemote = newRemoteEvent("BuyAndHatchEgg")
local FeedBlorbRemote = newRemoteEvent("FeedBlorb")
local BreedBlorbsRemote = newRemoteEvent("BreedBlorbs")
local PlaceOnStandRemote = newRemoteEvent("PlaceOnStand")
local RemoveFromStandRemote = newRemoteEvent("RemoveFromStand")
local RentBlorbRemote = newRemoteEvent("RentBlorb")

local DataUpdatedRemote = newRemoteEvent("DataUpdated") -- server -> client, full data snapshot
local NotifyRemote = newRemoteEvent("Notify") -- server -> client, short feedback message

-- // Helpers -------------------------------------------------------------------------

local function pushData(player)
	local data = PlayerDataManager.Get(player)
	if data then
		DataUpdatedRemote:FireClient(player, data)
	end
end

local function notify(player, message, isError)
	NotifyRemote:FireClient(player, message, isError == true)
end

local function handle(remote, fn)
	remote.OnServerEvent:Connect(function(player, ...)
		local ok, success, resultOrError = pcall(fn, player, ...)
		if not ok then
			warn(("RentABlorb: handler error for %s: %s"):format(remote.Name, tostring(success)))
			notify(player, "Something went wrong -- try again.", true)
			return
		end

		if success then
			pushData(player)
		else
			notify(player, tostring(resultOrError), true)
		end
	end)
end

-- // Remote wiring --------------------------------------------------------------------

handle(BuyAndHatchEggRemote, function(player, eggTypeId)
	return HatchingService.BuyAndHatch(player, eggTypeId)
end)

handle(FeedBlorbRemote, function(player, blorbId)
	return FeedingService.Feed(player, blorbId)
end)

handle(BreedBlorbsRemote, function(player, blorbIdA, blorbIdB)
	return BreedingService.Breed(player, blorbIdA, blorbIdB)
end)

handle(PlaceOnStandRemote, function(player, blorbId, slotIndex)
	return RentalService.PlaceOnStand(player, blorbId, slotIndex)
end)

handle(RemoveFromStandRemote, function(player, slotIndex)
	return RentalService.RemoveFromStand(player, slotIndex)
end)

RentBlorbRemote.OnServerEvent:Connect(function(renterPlayer, ownerUserId, slotIndex)
	local ok, success, resultOrError = pcall(RentalService.RentBlorb, renterPlayer, ownerUserId, slotIndex)
	if not ok then
		warn("RentABlorb: RentBlorb handler error: " .. tostring(success))
		notify(renterPlayer, "Something went wrong -- try again.", true)
		return
	end

	if success then
		pushData(renterPlayer)
		local ownerPlayer = Players:GetPlayerByUserId(ownerUserId)
		if ownerPlayer then
			pushData(ownerPlayer)
			notify(ownerPlayer, ("%s rented one of your Blorbs for %d Snacks!"):format(renterPlayer.Name, resultOrError.price), false)
		end
		notify(renterPlayer, "Rented! Buff active.", false)
	else
		notify(renterPlayer, tostring(resultOrError), true)
	end
end)

-- // Player lifecycle -----------------------------------------------------------------

Players.PlayerAdded:Connect(function(player)
	PlayerDataManager.Load(player)
	CustomerSimService.OnPlayerAdded(player)
	BaseAssignmentService.AssignBase(player)

	player.CharacterAdded:Connect(function()
		BaseAssignmentService.AssignBase(player)
	end)

	pushData(player)
end)

Players.PlayerRemoving:Connect(function(player)
	CustomerSimService.OnPlayerRemoving(player)
	BaseAssignmentService.ReleaseBase(player)
	PlayerDataManager.Release(player)
end)

game:BindToClose(function()
	PlayerDataManager.SaveAll()
end)

-- // Background loops -----------------------------------------------------------------

task.spawn(function()
	while true do
		task.wait(60)
		for _, player in ipairs(Players:GetPlayers()) do
			FeedingService.DecayTick(player, 1)
		end
	end
end)

task.spawn(function()
	while true do
		task.wait(5)
		RentalService.ExpireTick()
	end
end)

task.spawn(function()
	while true do
		task.wait(10)
		CustomerSimService.Tick()
		for _, player in ipairs(Players:GetPlayers()) do
			pushData(player) -- keeps client currency/hunger/stand UI reasonably fresh
		end
	end
end)

task.spawn(function()
	while true do
		task.wait(30)
		LeaderboardService.RefreshBoard()
	end
end)

task.spawn(function()
	while true do
		task.wait(BlorbData.Config.AutosaveIntervalSeconds)
		PlayerDataManager.SaveAll()
	end
end)
