-- Rent-a-Blorb -- generated by content_gen/luau_generator.py
-- Core loop: Players hatch, feed, and rent out absurd meme-mashup creatures called Blorbs to other players' bases for short-term buffs; learnable in under 15 minutes.
-- Hook: Instead of a one-off meme cash-grab, Blorbs generate ongoing rental income for their owners, giving the meme premise a light economy that can deepen post-launch (breeding, rare traits) rather than flattening after the initial spike.
-- Economy/social design: The rental marketplace is the core scarcity/trading loop; a breeding sink prevents rental-Blorb inflation; showing off rare Blorbs is the social hook.
-- AI would generate the initial wave of Blorb designs, names, and rental flavor text; a human needs to tune rental payout balance so the economy doesn't inflate within days.

-- Rent-a-Blorb -- client. Builds a minimal functional HUD (not a polished UI -- see
-- BUILD_NOTES.md) and wires ProximityPrompts on world parts tagged by CollectionService.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CollectionService = game:GetService("CollectionService")

local LocalPlayer = Players.LocalPlayer

local Remotes = ReplicatedStorage:WaitForChild("Remotes")
local BuyAndHatchEggRemote = Remotes:WaitForChild("BuyAndHatchEgg")
local FeedBlorbRemote = Remotes:WaitForChild("FeedBlorb")
local BreedBlorbsRemote = Remotes:WaitForChild("BreedBlorbs")
local PlaceOnStandRemote = Remotes:WaitForChild("PlaceOnStand")
local RemoveFromStandRemote = Remotes:WaitForChild("RemoveFromStand")
local RentBlorbRemote = Remotes:WaitForChild("RentBlorb")
local DataUpdatedRemote = Remotes:WaitForChild("DataUpdated")
local NotifyRemote = Remotes:WaitForChild("Notify")

local BlorbData = require(ReplicatedStorage:WaitForChild("BlorbShared"):WaitForChild("BlorbData"))

local latestData = nil
local selectedForBreeding = {} -- up to 2 blorbIds
local selectedForPlacement = nil -- one blorbId, consumed on next stand interaction

-- // HUD ------------------------------------------------------------------------------

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "BlorbHUD"
screenGui.ResetOnSpawn = false
screenGui.Parent = LocalPlayer:WaitForChild("PlayerGui")

local currencyLabel = Instance.new("TextLabel")
currencyLabel.Name = "Currency"
currencyLabel.Size = UDim2.new(0, 220, 0, 32)
currencyLabel.Position = UDim2.new(0, 12, 0, 12)
currencyLabel.BackgroundColor3 = Color3.fromRGB(20, 20, 28)
currencyLabel.TextColor3 = Color3.fromRGB(255, 230, 120)
currencyLabel.Font = Enum.Font.GothamBold
currencyLabel.TextSize = 18
currencyLabel.Text = "Snacks: --"
currencyLabel.Parent = screenGui

local notifyLabel = Instance.new("TextLabel")
notifyLabel.Name = "Notify"
notifyLabel.Size = UDim2.new(0, 320, 0, 28)
notifyLabel.Position = UDim2.new(0, 12, 0, 48)
notifyLabel.BackgroundTransparency = 1
notifyLabel.Font = Enum.Font.Gotham
notifyLabel.TextSize = 14
notifyLabel.TextXAlignment = Enum.TextXAlignment.Left
notifyLabel.Text = ""
notifyLabel.Parent = screenGui

local listFrame = Instance.new("ScrollingFrame")
listFrame.Name = "BlorbList"
listFrame.Size = UDim2.new(0, 320, 0, 300)
listFrame.Position = UDim2.new(0, 12, 0, 84)
listFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 28)
listFrame.BackgroundTransparency = 0.2
listFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
listFrame.AutomaticCanvasSize = Enum.AutomaticSize.Y
listFrame.ScrollBarThickness = 6
listFrame.Parent = screenGui

local listLayout = Instance.new("UIListLayout")
listLayout.SortOrder = Enum.SortOrder.LayoutOrder
listLayout.Padding = UDim.new(0, 4)
listLayout.Parent = listFrame

local buyBasicButton = Instance.new("TextButton")
buyBasicButton.Size = UDim2.new(0, 150, 0, 32)
buyBasicButton.Position = UDim2.new(0, 12, 0, 396)
buyBasicButton.Text = ("Buy Basic Egg (%d)"):format(BlorbData.Config.BasicEggPrice)
buyBasicButton.Font = Enum.Font.Gotham
buyBasicButton.TextSize = 13
buyBasicButton.Parent = screenGui

local buyRareButton = Instance.new("TextButton")
buyRareButton.Size = UDim2.new(0, 150, 0, 32)
buyRareButton.Position = UDim2.new(0, 172, 0, 396)
buyRareButton.Text = ("Buy Rare Egg (%d)"):format(BlorbData.Config.RareEggPrice)
buyRareButton.Font = Enum.Font.Gotham
buyRareButton.TextSize = 13
buyRareButton.Parent = screenGui

local breedButton = Instance.new("TextButton")
breedButton.Size = UDim2.new(0, 310, 0, 32)
breedButton.Position = UDim2.new(0, 12, 0, 434)
breedButton.Text = "Breed Selected (pick 2 below)"
breedButton.Font = Enum.Font.Gotham
breedButton.TextSize = 13
breedButton.Parent = screenGui

buyBasicButton.MouseButton1Click:Connect(function()
	BuyAndHatchEggRemote:FireServer("BasicEgg")
end)
buyRareButton.MouseButton1Click:Connect(function()
	BuyAndHatchEggRemote:FireServer("RareEgg")
end)
breedButton.MouseButton1Click:Connect(function()
	if #selectedForBreeding == 2 then
		BreedBlorbsRemote:FireServer(selectedForBreeding[1], selectedForBreeding[2])
		selectedForBreeding = {}
	end
end)

local function rebuildList()
	for _, child in ipairs(listFrame:GetChildren()) do
		if child:IsA("Frame") then
			child:Destroy()
		end
	end

	if not latestData then
		return
	end

	local order = 0
	for blorbId, blorb in pairs(latestData.blorbs) do
		order += 1

		local row = Instance.new("Frame")
		row.Name = blorbId
		row.Size = UDim2.new(1, -8, 0, 64)
		row.BackgroundColor3 = Color3.fromRGB(32, 32, 44)
		row.LayoutOrder = order
		row.Parent = listFrame

		local info = Instance.new("TextLabel")
		info.Size = UDim2.new(1, -8, 0, 36)
		info.Position = UDim2.new(0, 4, 0, 2)
		info.BackgroundTransparency = 1
		info.Font = Enum.Font.Gotham
		info.TextSize = 12
		info.TextXAlignment = Enum.TextXAlignment.Left
		info.TextColor3 = Color3.fromRGB(230, 230, 240)
		info.Text = ("%s [%s]\nHunger %d/100 -- %s"):format(
			blorb.species, blorb.rarityId, blorb.hunger, BlorbData.BuffTypes[blorb.buffTypeId].label
		)
		info.Parent = row

		local feedBtn = Instance.new("TextButton")
		feedBtn.Size = UDim2.new(0, 60, 0, 22)
		feedBtn.Position = UDim2.new(0, 4, 0, 38)
		feedBtn.Text = "Feed"
		feedBtn.TextSize = 11
		feedBtn.Parent = row
		feedBtn.MouseButton1Click:Connect(function()
			FeedBlorbRemote:FireServer(blorbId)
		end)

		local placeBtn = Instance.new("TextButton")
		placeBtn.Size = UDim2.new(0, 90, 0, 22)
		placeBtn.Position = UDim2.new(0, 68, 0, 38)
		placeBtn.Text = blorb.standSlot and ("On stand #" .. blorb.standSlot) or "Select to place"
		placeBtn.TextSize = 11
		placeBtn.Parent = row
		placeBtn.MouseButton1Click:Connect(function()
			if blorb.standSlot then
				RemoveFromStandRemote:FireServer(blorb.standSlot)
			else
				selectedForPlacement = blorbId
				notifyLabel.Text = "Selected for placement -- walk up to an empty stand slot."
			end
		end)

		local breedBtn = Instance.new("TextButton")
		breedBtn.Size = UDim2.new(0, 90, 0, 22)
		breedBtn.Position = UDim2.new(0, 162, 0, 38)
		local isSelected = table.find(selectedForBreeding, blorbId) ~= nil
		breedBtn.Text = isSelected and "Selected" or "Pick to breed"
		breedBtn.TextSize = 11
		breedBtn.Parent = row
		breedBtn.MouseButton1Click:Connect(function()
			if isSelected then
				local idx = table.find(selectedForBreeding, blorbId)
				table.remove(selectedForBreeding, idx)
			elseif #selectedForBreeding < 2 then
				table.insert(selectedForBreeding, blorbId)
			end
			rebuildList()
		end)
	end
end

DataUpdatedRemote.OnClientEvent:Connect(function(data)
	latestData = data
	currencyLabel.Text = ("Snacks: %d"):format(data.currency)
	rebuildList()
end)

NotifyRemote.OnClientEvent:Connect(function(message, isError)
	notifyLabel.TextColor3 = isError and Color3.fromRGB(255, 120, 120) or Color3.fromRGB(150, 255, 150)
	notifyLabel.Text = message
	task.delay(4, function()
		if notifyLabel.Text == message then
			notifyLabel.Text = ""
		end
	end)
end)

-- // World interactions (egg stalls + rental stands) --------------------------------

local function onEggStallPrompt(part)
	local eggType = part:GetAttribute("EggType") or "BasicEgg"
	BuyAndHatchEggRemote:FireServer(eggType)
end

local function onRentalStandPrompt(part)
	local ownerUserId = part:GetAttribute("OwnerUserId")
	local slotIndex = part:GetAttribute("SlotIndex")
	if not ownerUserId or not slotIndex then
		return
	end

	if ownerUserId == LocalPlayer.UserId then
		if selectedForPlacement then
			PlaceOnStandRemote:FireServer(selectedForPlacement, slotIndex)
			selectedForPlacement = nil
		else
			RemoveFromStandRemote:FireServer(slotIndex)
		end
	else
		RentBlorbRemote:FireServer(ownerUserId, slotIndex)
	end
end

local function wirePrompt(part, handler)
	local prompt = part:FindFirstChildOfClass("ProximityPrompt")
	if prompt then
		prompt.Triggered:Connect(function()
			handler(part)
		end)
	end
end

for _, part in ipairs(CollectionService:GetTagged("EggStall")) do
	wirePrompt(part, onEggStallPrompt)
end
CollectionService:GetInstanceAddedSignal("EggStall"):Connect(function(part)
	wirePrompt(part, onEggStallPrompt)
end)

for _, part in ipairs(CollectionService:GetTagged("RentalStand")) do
	wirePrompt(part, onRentalStandPrompt)
end
CollectionService:GetInstanceAddedSignal("RentalStand"):Connect(function(part)
	wirePrompt(part, onRentalStandPrompt)
end)
