-- Rent-a-Blorb -- generated by content_gen/luau_generator.py
-- Core loop: Players hatch, feed, and rent out absurd meme-mashup creatures called Blorbs to other players' bases for short-term buffs; learnable in under 15 minutes.
-- Hook: Instead of a one-off meme cash-grab, Blorbs generate ongoing rental income for their owners, giving the meme premise a light economy that can deepen post-launch (breeding, rare traits) rather than flattening after the initial spike.
-- Economy/social design: The rental marketplace is the core scarcity/trading loop; a breeding sink prevents rental-Blorb inflation; showing off rare Blorbs is the social hook.
-- AI would generate the initial wave of Blorb designs, names, and rental flavor text; a human needs to tune rental payout balance so the economy doesn't inflate within days.

-- Rent-a-Blorb -- shared game data (rarity tiers, species, buffs, egg types, tunable
-- constants). Read by both server (authoritative rolls/economy) and client (UI display
-- only -- the client never trusts its own copy for anything that moves currency).

local BlorbData = {}

BlorbData.Config = {
	StarterCurrency = 100,
	MaxStandSlots = 3,

	HungerMax = 100,
	HungerDecayPerMinute = 4,
	FeedCost = 5,
	FeedRestoreAmount = 40,
	GrumpyHungerThreshold = 20, -- below this, rental buffs are halved
	StarvedHungerThreshold = 0, -- at this point the Blorb can't be rented at all

	BasicEggPrice = 20,
	RareEggPrice = 100,

	BreedCost = 50,
	BreedTierUpChance = 0.12, -- chance the offspring rolls one rarity tier above the better parent

	RentDurationSeconds = 180,
	CustomerIntervalMin = 45,
	CustomerIntervalMax = 120,
	CustomerPayoutMultiplier = 0.4, -- NPC customers pay less than a real player would -- P2P renting is the better economy

	AutosaveIntervalSeconds = 120,
}

-- Rarity order matters for breeding tier-up logic (index+1 = next tier up)
BlorbData.RarityOrder = { "Common", "Uncommon", "Rare", "Epic", "Mythic" }

BlorbData.RarityTiers = {
	Common =   { hatchWeight = 55, rentPrice = 5,   buffMagnitude = 1.00, scoreValue = 1 },
	Uncommon = { hatchWeight = 25, rentPrice = 12,  buffMagnitude = 1.15, scoreValue = 3 },
	Rare =     { hatchWeight = 13, rentPrice = 30,  buffMagnitude = 1.35, scoreValue = 8 },
	Epic =     { hatchWeight = 5,  rentPrice = 75,  buffMagnitude = 1.60, scoreValue = 20 },
	Mythic =   { hatchWeight = 2,  rentPrice = 200, buffMagnitude = 2.00, scoreValue = 50 },
}

-- Rare Egg reweights the odds toward the top of the table -- still can't guarantee Mythic.
BlorbData.RareEggHatchWeights = {
	Common = 25, Uncommon = 30, Rare = 25, Epic = 15, Mythic = 5,
}

-- Original meme-mashup species names -- deliberately not referencing any existing IP.
BlorbData.Species = {
	"Turbo Sock Goblin",
	"Crusty Waffle Pigeon",
	"Glitch Noodle Toaster",
	"Sus Rizz Raccoon",
	"Feral Cardboard Wizard",
	"Static Pickle Dragon",
	"Doomscroll Duckling",
	"Buffering Hamster Knight",
}

BlorbData.BuffTypes = {
	SpeedBoost = { label = "Turbo Legs", statAffected = "WalkSpeed" },
	JumpBoost = { label = "Rizz Hops", statAffected = "JumpPower" },
	LuckBoost = { label = "Sus Luck", statAffected = "HatchLuck" },
	SnackMultiplier = { label = "Snack Rizz", statAffected = "SnackIncome" },
}

BlorbData.BuffTypeIds = { "SpeedBoost", "JumpBoost", "LuckBoost", "SnackMultiplier" }

return BlorbData
